"""Reusable models and renderers for research-software project files."""

from .contract import RSM_SCHEMA_URL, validate_contract_compatibility
from .models import (
    ChangelogModel,
    CitationModel,
    CodeMetaModel,
    CodeOfConductModel,
    Containerization,
    DataFormat,
    EdamTerm,
    ExternalDependency,
    ExternalService,
    FileTemplateModel,
    FunctionIo,
    Funding,
    GovernanceModel,
    Interface,
    LicenseModel,
    OperatingSystem,
    Organization,
    PersistentIdentifier,
    Person,
    ProgrammingLanguage,
    Publication,
    Registry,
    RelatedSoftware,
    RSMMetadata,
    SecurityModel,
    SoftwareFunction,
    SupportModel,
    SupportRoute,
    ZenodoModel,
)
from .renderer import GeneratedFile, render_file, render_many, render_text

__all__ = [
    "RSM_SCHEMA_URL",
    "ChangelogModel",
    "CitationModel",
    "CodeMetaModel",
    "CodeOfConductModel",
    "Containerization",
    "DataFormat",
    "EdamTerm",
    "ExternalDependency",
    "ExternalService",
    "FileTemplateModel",
    "FunctionIo",
    "Funding",
    "GeneratedFile",
    "GovernanceModel",
    "Interface",
    "LicenseModel",
    "OperatingSystem",
    "Organization",
    "PersistentIdentifier",
    "Person",
    "ProgrammingLanguage",
    "Publication",
    "RSMMetadata",
    "Registry",
    "RelatedSoftware",
    "SecurityModel",
    "SoftwareFunction",
    "SupportModel",
    "SupportRoute",
    "ZenodoModel",
    "render_file",
    "render_many",
    "render_text",
    "validate_contract_compatibility",
]
